# -*- coding: utf-8 -*-
"""pro 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wlDo_Mn_G6lxnl30aVVLVFHfdk_cCmnd
"""

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

data_set = pd.read_csv('/content/drive/MyDrive/Software Project /Agricultural-Dataset.csv')
#data_set = pd.read_csv('/content/drive/MyDrive/Software Project /Agricultural-Dataset.csv')

data_set

data_set.head()

sb.countplot(x='Year', data=data_set, hue='AUS')
sb.count

Area_name = pd.Series(["Dhaka", "Narsindi", "Tangail"])
Area_area = pd.Series(["470", "252", "497"])

Area_name

Area_area

Area_data = pd.DataFrame({"Name":Area_name, "Country":Area_area})
Area_data

data_set.dtypes

data_set.index

data_set.columns

data_set.info()         # will show the info of each missing column

data_set.mean()         # mean function give the average of numarical column

data_set.groupby(["District"]).mean()       # grouping data using club name & function groupby

data_set2 = data_set.drop(["Year"],axis= 1 ) 

data_set2.groupby(["District"]).mean()

data_set2.groupby(["District"]).sum()

# plotting Data 

data_set["Area"].plot()

data_set["Area"].hist()

data_set['District'] = data_set['District'].str.upper()
data_set

data_set_shuffled =data_set.sample(frac=1)

data_set_shuffled

data_set2.sort_values(by=['Total Paddy', 'Total Fertilizer'])

data_set2.sort_values(by=['Area'] , ascending = True)

data_set.sample(frac=0.2)

data_set.loc[[1,5,10,15]]

data_set.loc[10:25]

data_set['District']

data_set.plot.line(y='Humidity', x='Year',figsize = (25,10))

data_set3 = data_set.copy()
data_set2.set( xaxis lab )

data_set2['Total land '].head(10).plot(figsize = (25,10),kind="bar",legend=None);

data_set3.plot.scatter(figsize = (25,10),x= 'Total Paddy',y= 'Total soil',alpha=1)

data_set3.groupby(['District']).plot.area(figsize = (15,10),subplots = False,legend=None,xlabel="new x", ylabel="new y")

data_set3.groupby(['Year'])['Total soil'].sum().plot(figsize = (25,10),kind = 'barh')

data_set2.head(4).plot.pie(y='Avg_rainfall', labels=["AA", "BB", "CC", "DD"],autopct="%.2f", fontsize=10,  figsize=(20, 15 ))

data_set3.plot.hexbin(x = 'Area', y = "Total soil",figsize = (20,10) ,gridsize = 20 )

new_dataset = data_set[['Total Paddy','Avg_rainfall']].copy()

Mean =Total Paddy / Avg_rainfall
dk=pd.new_dataset({"Paddy":Total Paddy,"Distance(KM)":Avg_rainfall,"Velocity":Mean})

