# -*- coding: utf-8 -*-
"""Team_infinity-Project_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wlDo_Mn_G6lxnl30aVVLVFHfdk_cCmnd
"""

import pandas as pd
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt

data_set = pd.read_csv('/content/drive/MyDrive/Software Project /Agricultural-Dataset.csv')
#data_set = pd.read_csv('/content/drive/MyDrive/Software Project /Agricultural-Dataset.csv')

data_set

data_set.head()

data_set3 = data_set.copy()

data_set.index

"""Susmoy"""

data_set2.describe()

data_set2.sort_values(by=['Total Paddy', 'Total Fertilizer'])

Area_name = pd.Series(["Dhaka", "Narsindi", "Tangail"])
Area_area = pd.Series(["470", "252", "497"])

Area_name

Area_area

Area_data = pd.DataFrame({"Name":Area_name, "Country":Area_area})
Area_data

data_set.plot.line(y='Humidity', x='Year',figsize = (10,10))

data_set2['Total land '].head(10).plot(figsize = (10,10),kind="bar",legend=None);

"""Rasel"""

data_set['District']

data_set.columns

data_set2.sort_values(by=['Area'] , ascending = True)

data_set.loc[[1,5,10,15]]

data_set.loc[10:25]

x = np.linspace(0, 10, 1000)
fig, ax = plt.subplots(figsize=(10,10))

ax.plot(x, np.sin(x), color="Red", label='Sine')
ax.plot(x, np.cos(x), color= 'Green', label='Cosine')
leg = ax.legend();

ser = pd.Series(data_set3.Avg_temp)
ser.plot.kde(figsize= (10,10));

boxplot = data_set3.boxplot(column=['Total soil', 'Total Paddy', 'Total Fertilizer'],figsize=(10,10))

"""Omar Jidan"""

data_set2.groupby(["District"]).sum()

data_set2 = data_set.drop(["Year"],axis= 1 ) 

data_set2.groupby(["District"]).mean()

data_set['District'] = data_set['District'].str.upper()
data_set

Count = sb.countplot(x='Year', data=data_set, hue='AUS' )

# plotting Data 

data_set["Area"].plot(figsize = (10,10))

data_set["Area"].hist(figsize = (10,10))

"""Asad"""

data_set.sample(frac=0.2)

data_set_shuffled =data_set.sample(frac=1)

data_set_shuffled

data_set3.plot.scatter(figsize = (10,10),x= 'Total Paddy',y= 'Total soil',alpha=1)

data_set3.groupby(['District']).plot.area(figsize = (10,10),subplots = False,legend=None,xlabel="Year", ylabel="DATA")

"""Nazam bin sadi"""

data_set3.groupby(['Year'])['Total soil'].sum().plot(figsize = (10,10),kind = 'barh')

data_set2.head(20).plot.pie(y='Avg_rainfall', autopct="%.2f", fontsize=10,  figsize=(10, 8 ),legend =None)

data_set3.plot.hexbin(x = 'Area', y = "Total soil",figsize = (10,10) ,gridsize = 20 )

data_set.info()

data_set3.duplicated()

data_set.dtypes

data_set.mean()